#version: '3.8'

services:
  # NGINX Web Server Service
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: unless-stopped

  # MARIADB DATABASE
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      # Database connection for mariadb
      # variables used to configure the database connection
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    restart: unless-stopped

  # WORDPRESS
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
      - redis
    environment:
      # Database connection for WordPress
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      # WordPress admin configuration
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
      #network
    restart: unless-stopped

  # BONUS: redis
  redis:
    container_name: redis
    build: 
      context: ./bonus/redis
      dockerfile: Dockerfile
    #ports: NO ports needed (internal connection only)
    volumes:
      - redis_data:/var/www/html
    networks:
      - inception_network
    restart: unless-stopped
    
  # BONUS: adminer
  adminer:
    container_name: adminer
    build: 
      context: ./bonus/adminer
      dockerfile: Dockerfile
    volumes:
      - adminer_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception_network
    restart: unless-stopped

# VOLUMES #Named volumes for data persistence
volumes:
  # mariadb volume
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_DIR}/mariadb_data
      #device: /home/${USER}/data/mariadb (alternative way to write host path)
      o: bind
  
  # wordpress volume
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_DIR}/wordpress_data
      o: bind

  # redis volume
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_DIR}/redis_data
      o: bind

  # adminer volume  
  adminer_data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_DIR}/adminer_data
      o: bind

# NETWORKS # Custom network for service communication
networks:
  inception_network:
    driver: bridge
