version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx_test
    ports:
      - "8080:443"
    # Remove dependencies for testing
    # depends_on:
    #   - wordpress
    networks:
      - inception_network

networks:
  inception_network:
    driver: bridge
